name: sync-code-o-dh-012
on:
  push:
    branches:
      - main # Kích hoạt workflow khi đẩy lên nhánh main
  workflow_dispatch:
  schedule:
    - cron: "30 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: sync-code-o-dh-012
    # Set environment variables for the entire job
    env:
      OAESFILE: ${{ secrets.OAESFILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Decrypt oAESFile
        shell: bash
        run: |
          if [ -f "./oAESFile.js" ]; then 
            node ./oAESFile.js --de ${{ secrets.OAESFILE }} ./dist; 
            git log -1;
          fi
      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Run sync-code-Listener
        run: |
          npm install -g pm2
          pm2 start ./dist/dist-sync-code-o-dh-012.js --name "dist-sync-code-o-dh-012" --watch
          pm2 save  # Save the PM2 process list for restart
          pm2 list  # Display PM2 processes for logging
      - name: Keep PM2 running
        run: |
          pm2 monit  # Keeps PM2 running for the duration of the action

      - name: Upload build artifacts v4
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/ # Tải lên thư mục build (dist)
          retention-days: 10 # Định nghĩa thời gian tồn tại (ở đây là 30 ngày)
          compression-level: 9 # maximum compression
