name: sync-manual
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: sync-manual
    env:
      OAESFILE: ${{ secrets.OAESFILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pm2
        run: npm install -g pm2
      - name: Run sync-manual
        run: |
          node ./oAESFile.js --de ${{ secrets.OAESFILE }} ./dist
          node ./dist/dist-sync-manual.js
